# Generated by Django 4.2.6 on 2023-10-17 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Station',
        ),
    ]
