# Generated by Django 4.2.6 on 2023-10-19 11:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0003_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("route", models.PositiveIntegerField()),
                ("plate", models.CharField(max_length=16)),
                ("in_stop_id", models.PositiveIntegerField()),
                ("velocity", models.FloatField()),
                ("distance_from_src", models.FloatField()),
            ],
        ),
    ]
