# Generated by Django 4.2.6 on 2023-11-01 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_bus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bus',
        ),
    ]
