# Generated by Django 4.2.6 on 2023-11-01 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_delete_bus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.PositiveIntegerField()),
                ('number_plate', models.CharField(max_length=16)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('velocity', models.FloatField()),
                ('timestamp', models.CharField(max_length=16)),
            ],
        ),
    ]
